name: Build and Test Package

on: [push, pull_request]

jobs:
  tests:
    name: "Testing"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.14"]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .
          pip install .[dev,tests]

      - name: Build package
        run: |
          pyproject-build

      - name: Run tests
        run: |
          pytest -v -s
        env:
          POD_NC_URL: ${{ secrets.POD_NC_URL }}
          POD_NC_USERNAME: ${{ secrets.POD_NC_USERNAME }}
          POD_NC_ACCESSTOKEN: ${{ secrets.POD_NC_ACCESSTOKEN }}
          POD_USERNAME: ${{ secrets.POD_USERNAME }}
          POD_PASSWORD: ${{ secrets.POD_PASSWORD }}


  build_and_deploy:
    name: "Build and Deploy"
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .
          pip install .[dev,tests]

      - name: Build package
        run: |
          pyproject-build

      - name: Run tests
        run: |
          pytest -v

      - name: Publish package to Test PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
          verbose: true
          skip-existing: true
          repository-url: https://test.pypi.org/legacy/

      - name: Publish package to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
          verbose: true
